steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - '-f'
      - Dockerfile
      - '-t'
      - test_runner
      - .
    id: Build test runner
  - name: test_runner
    args:
      - pytest
    id: Tests
  - name: test_runner
    args:
      - pytest
      - '--black'
      - '-m'
      - 'black'
      - '&&'
      - pytest
      - '--isort'
      - '-m'
      - 'isort'
    id: Linters
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_RUN_NAME:$COMMIT_SHA'
      - .
    id: Build app
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_RUN_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_RUN_NAME
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_RUN_NAME:$COMMIT_SHA'
      - '--region'
      - europe-west4
    id: Deploy
    entrypoint: gcloud
images:
  - 'gcr.io/$PROJECT_ID/$_RUN_NAME:$COMMIT_SHA'
