"""init

Revision ID: 84d94c61b830
Revises: 
Create Date: 2023-08-22 20:42:37.015243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d94c61b830'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_title', table_name='images')
    op.drop_index('ix_images_uuid', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_notes_title', table_name='notes')
    op.drop_index('ix_notes_uuid', table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('uuid', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.Column('image_uuid', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['image_uuid'], ['images.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_notes_uuid', 'notes', ['uuid'], unique=False)
    op.create_index('ix_notes_title', 'notes', ['title'], unique=False)
    op.create_table('images',
    sa.Column('uuid', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_images_uuid', 'images', ['uuid'], unique=False)
    op.create_index('ix_images_title', 'images', ['title'], unique=False)
    # ### end Alembic commands ###
